export const localTracks = [
  {
    id: 'wishes',
    title: 'Wishes',
    artist: 'Personal Track',
    duration: 0,
    cover: '/covers/wishes-cover.jpg',
    src: '/audio/wishes-music.mp3',
    blurb: 'A personal favorite in your collection.',
  },
  {
    id: 'jhol',
    title: 'Jhol',
    artist: 'Personal Track',
    duration: 0,
    cover: '/covers/jhol-cover.jpg',
    src: '/audio/jhol-music.mp3',
    blurb: 'Another track from your collection.',
  },
  {
    id: 'bargad',
    title: 'Bargad',
    artist: 'Personal Track',
    duration: 0,
    cover: '/covers/bargad-cover.jpg',
    src: '/audio/bargad-music.mp3',
    blurb: 'A new track added to your player.',
  },
  {
    id: 'chaandni',
    title: 'Chaandni',
    artist: 'Personal Track',
    duration: 0,
    cover: '/covers/chaandni-cover.jpg',
    src: '/audio/chaandni-music.mp3',
    blurb: 'A smooth track in your collection.',
  },
  {
    id: 'palpal',
    title: 'Palpal',
    artist: 'Personal Track',
    duration: 0,
    cover: '/covers/palpal-cover.jpg',
    src: '/audio/palpal-music.mp3',
    blurb: 'Another song ready to play.',
  },
];
